-- Syslog endpoints: the record a customer creates, names and switches off.
--
-- Deliberately THIN. The credential is an ordinary `api_keys` row with the new
-- `collector` scope, which is what already carries the hash lookup, the
-- per-key rate limit, `last_used_at`, revocation and the org stamp. A second
-- credential kind would have re-implemented all five, and `logs.source` already
-- records the key NAME per line — so "which site is sending too much" is
-- answerable today without anything new.
--
-- What this table adds is what an api_keys row cannot hold: a device prefix,
-- and a place for the managed-endpoint and tunnel columns of the later stages
-- to hang off.
--
-- There is no `last_seen_at` on purpose: `api_keys.last_used_at` is already
-- touched on every authenticated request, so a column here would be a second
-- write on the hottest path answering the same question slightly differently.
CREATE TABLE IF NOT EXISTS syslog_endpoints (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  org_id        UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  -- SET NULL rather than CASCADE: revoking the key must not delete the endpoint
  -- and its configuration. A keyless endpoint is a visible "rotate me" state;
  -- a vanished one is a support ticket.
  api_key_id    BIGINT REFERENCES api_keys(id) ON DELETE SET NULL,
  device_prefix TEXT,
  enabled       SMALLINT NOT NULL DEFAULT 1,
  created_by    UUID REFERENCES users(id),
  created_at    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_syslog_endpoints_org ON syslog_endpoints(org_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_syslog_endpoints_key ON syslog_endpoints(api_key_id)
  WHERE api_key_id IS NOT NULL;
