'use strict';
/* The storage shim's own semantics.
 *
 * ── Why this needs a harness of its own ─────────────────────────────────────
 *
 * Phase 4 converts ~700 call sites to go through `src/db/shim.js`. Every one of
 * them inherits whatever this file does. A mistake here is not one bug, it is
 * the same bug 700 times, and three of the four guarantees are ones nobody
 * would think to test at a call site:
 *
 *   - a missed `await` THROWS instead of yielding a truthy Promise
 *   - `changes` counts rows, because forty at-most-once gates decide on it
 *   - `lastInsertRowid` is refused rather than returning undefined
 *   - a nested `withTx` joins the open transaction rather than opening a second
 *
 * The strict-thenable checks are the ones worth reading twice. A Promise is
 * truthy and has no useful properties, so `rows.length` is `undefined`,
 * `rows.filter(...)` keeps everything, and `JSON.stringify(rows)` is `"{}"` —
 * all without an error. That is the failure class this whole port is about, and
 * this file is where it is pinned.
 *
 * It used to run against SQLite on purpose — the shim shipped on the old driver
 * so async correctness was settled while the synchronous path was still there to
 * compare against — and it was skipped when the suite moved to Postgres. That
 * made every guarantee above untested on the engine that actually serves. It
 * runs on Postgres now, and ONE section changed its claim rather than its
 * wording: two overlapping transactions used to have to SERIALISE, because
 * better-sqlite3 had a single connection and the shim took a lock to stop the
 * second BEGIN failing. With a pool there is no lock and no serialisation —
 * they genuinely run at once, which is what the pool exists for, and the check
 * says that instead.
 *
 * Boots no server and needs no port; it needs the DATABASE_URL run-e2e.js hands
 * it.  cd server && node run-e2e.js shim
 */
const { chk, report, die } = require('./e2e-lib').harness();

process.env.OPSCAT_SECRET = 'e2e-shim-secret';

const q = require('./src/db/shim');

const st = {
  ins: q.prepare('INSERT INTO shim_probe (name) VALUES (?)'),
  byName: q.prepare('SELECT * FROM shim_probe WHERE name = ?'),
  allRows: q.prepare('SELECT * FROM shim_probe ORDER BY id'),
  claim: q.prepare('UPDATE shim_probe SET claimed_at = ? WHERE name = ? AND claimed_at IS NULL'),
};

async function main() {
  // A table of our own rather than one of the app's: these checks claim things
  // about the SHIM, and a probe table cannot be broken by a schema change.
  await q.exec(`CREATE TABLE shim_probe (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE,
    claimed_at BIGINT)`);
  chk('exec() applies multi-statement DDL', !!(await q.get(
    "SELECT 1 AS ok FROM information_schema.tables WHERE table_name = 'shim_probe'")));

  // ── 1. the strict thenable ────────────────────────────────────────────────
  // Each of these is a real shape from the codebase, and each one currently
  // fails SILENTLY when the await is missing.
  const pending = st.allRows.all();
  const throws = (name, fn) => {
    let e = null;
    try { fn(); } catch (err) { e = err; }
    chk(name, e !== null && /unawaited DB result/.test(String(e.message)), String(e));
  };
  // Every line below is a deliberate missed await — that is the thing under
  // test. The type gate covers the harnesses too (see tsconfig.json), so it
  // flags them, and it is RIGHT to. `@ts-expect-error` says so out loud, and
  // has the property a blanket suppression would not: if one of these ever
  // stops being a type error, the pragma itself errors and somebody has to
  // find out why the shim's types went quiet.
  // @ts-expect-error — reading a property off a pending query is the bug being proven
  throws('reading .length on an unawaited result throws', () => pending.length);
  // @ts-expect-error — deliberate
  throws('…so does .map', () => pending.map);
  // @ts-expect-error — deliberate
  throws('…so does indexing', () => pending[0]);
  // @ts-expect-error — deliberate
  throws('…so does spreading', () => [...pending]);
  // @ts-expect-error — deliberate
  throws('…so does for..of', () => { for (const r of pending) void r; });
  throws('…so does JSON.stringify', () => JSON.stringify(pending));
  // @ts-expect-error — deliberate
  throws("…so does `'length' in rows`", () => ('length' in pending));
  throws('…so does string interpolation, which would log "[object Promise]"',
    () => `${pending}`);
  chk('…but awaiting it returns real rows', Array.isArray(await pending));

  // then/catch/finally must still work — the value IS a promise, and an
  // unhandled rejection has to be catchable by the route's error handler.
  let caught = null;
  await q.prepare('SELECT * FROM no_such_table').all().catch((e) => { caught = e; });
  chk('a failing statement rejects rather than throwing synchronously', caught !== null);

  // ── 2. insert() and the lastInsertRowid refusal ───────────────────────────
  const id = await st.ins.insert('alpha');
  chk('insert() returns the new integer id', typeof id === 'number' && id > 0, String(id));
  const back = await st.byName.get('alpha');
  chk('…and it is the row that was actually inserted', back && back.id === id);

  const res = await st.ins.run('beta');
  chk('run() reports one change', res.changes === 1, String(res.changes));
  let rowidErr = null;
  try { void res.lastInsertRowid; } catch (e) { rowidErr = e; }
  chk('reading lastInsertRowid through the shim throws rather than returning undefined',
    rowidErr !== null && /use stmt\.insert\(\)/.test(String(rowidErr.message)), String(rowidErr));
  // …and it must not show up in a spread or a JSON body either, or a converted
  // call site would serialise a getter that throws.
  chk('…and it is not enumerable, so { ...res } and JSON.stringify are safe',
    !Object.keys(res).includes('lastInsertRowid') && JSON.stringify(res) !== undefined);

  // An INSERT that already says RETURNING must not get a second clause.
  const explicit = q.prepare('INSERT INTO shim_probe (name) VALUES (?) RETURNING id');
  chk('an explicit RETURNING is not duplicated', (await explicit.get('gamma')).id > 0);

  // ── 3. changes is rows affected — forty gates depend on it ────────────────
  await st.ins.run('claimable');
  const first = await st.claim.run(1000, 'claimable');
  const second = await st.claim.run(1001, 'claimable');
  chk('the first claim of a row changes one row', first.changes === 1, String(first.changes));
  chk('…and the second changes none — the gate is the WHERE, not a JS check',
    second.changes === 0, String(second.changes));
  chk('…and the winner\'s value is the one that stuck',
    (await st.byName.get('claimable')).claimed_at === 1000);

  const nothing = await st.claim.run(1, 'nobody-by-that-name');
  chk('a WHERE that matches nothing reports zero changes', nothing.changes === 0);

  // ── 4. transactions ───────────────────────────────────────────────────────
  await q.withTx(async () => { await st.ins.run('tx-committed'); });
  chk('a committed transaction keeps its write', !!(await st.byName.get('tx-committed')));

  let boom = null;
  try {
    await q.withTx(async () => {
      await st.ins.run('tx-rolled-back');
      throw new Error('deliberate');
    });
  } catch (e) { boom = e; }
  chk('a throw inside withTx propagates', boom && boom.message === 'deliberate');
  chk('…and the write is gone', !(await st.byName.get('tx-rolled-back')));

  // Nesting must JOIN. A second BEGIN would take a second pooled client, which
  // deadlocks against the first's locks while its COMMIT publishes half the
  // outer transaction's work.
  let nested = null;
  await q.withTx(async () => {
    await st.ins.run('outer');
    nested = q.inTx();
    await q.withTx(async () => { await st.ins.run('inner'); });
    chk('a nested withTx joins rather than opening a second transaction',
      !!(await st.byName.get('inner')));
  });
  chk('inTx() reports an open transaction while one is open', nested !== null);
  chk('…and nothing once it has closed', q.inTx() === null);

  // The rollback has to unwind the nested write too, or "joins the outer
  // transaction" is a claim about BEGIN and not about atomicity.
  try {
    await q.withTx(async () => {
      await st.ins.run('outer-doomed');
      await q.withTx(async () => { await st.ins.run('inner-doomed'); });
      throw new Error('deliberate');
    });
  } catch { /* expected */ }
  chk('rolling back the outer transaction unwinds the nested write too',
    !(await st.byName.get('inner-doomed')) && !(await st.byName.get('outer-doomed')));

  /* Two transactions at once, one of them yielding for a NON-database reason —
   * a cloud API, a webhook, an LLM, which is exactly what the transactions in
   * this codebase await (the provisioning saga, the automation actions).
   *
   * This section is where retiring SQLite changed the ANSWER and not just the
   * driver. better-sqlite3 had one connection, so a second BEGIN raised
   * `cannot start a transaction within a transaction` — a 500 on a real
   * request, only under concurrency — and the shim took a promise-chain lock to
   * serialise them. That lock is gone: each withTx pins its own pooled client,
   * so they overlap, and the quick one must NOT be stuck behind the slow one.
   * If the lock were ever reintroduced "for safety" it would silently
   * serialise every transaction in the app, and this is the check that says so.
   */
  const order = [];
  const slow = q.withTx(async () => {
    await st.ins.run('tx-slow-a');
    await new Promise((r) => setTimeout(r, 30));   // a network call, say
    await st.ins.run('tx-slow-b');
    order.push('slow');
  });
  const quick = q.withTx(async () => { await st.ins.run('tx-quick'); order.push('quick'); });
  const both = await Promise.allSettled([slow, quick]);
  chk('two overlapping transactions both commit — the second is not refused',
    both.every((r) => r.status === 'fulfilled'),
    both.map((r) => r.status + (r.reason ? `: ${r.reason.message}` : '')).join(' | '));
  chk('…and they genuinely overlap: the quick one does not wait for the slow one',
    order.join(',') === 'quick,slow', order.join(','));
  chk('…with every write landing', !!(await st.byName.get('tx-slow-b')) && !!(await st.byName.get('tx-quick')));

  // A transaction that throws must release its client. Otherwise one failed
  // request leaks a connection and the tenth one hangs on an exhausted pool.
  await q.withTx(async () => { throw new Error('deliberate'); }).catch(() => {});
  await q.withTx(async () => { await st.ins.run('after-failure'); });
  chk('a failed transaction releases its client rather than leaking it',
    !!(await st.byName.get('after-failure')));

  // ── 5. the handle is lazy ─────────────────────────────────────────────────
  // If the shim compiled at prepare() time, requiring any module would need a
  // live connection — which is exactly what a pool cannot promise at
  // module-load time, since 766 statements are defined at module scope.
  let prepErr = null;
  let handle = null;
  try { handle = q.prepare('SELECT * FROM definitely_not_a_table'); } catch (e) { prepErr = e; }
  chk('preparing an invalid statement does not throw at prepare() time', prepErr === null);
  chk('…the SQL is kept for diagnostics', handle.source.includes('definitely_not_a_table'));
  let useErr = null;
  await handle.all().catch((e) => { useErr = e; });
  chk('…and it fails when it is actually used', useErr !== null);

  report();
}

main().catch(die);
