'use strict';
const crypto = require('crypto');

const now = () => Date.now();
const sha256 = (s) => crypto.createHash('sha256').update(s).digest('hex');
const randHex = (bytes = 16) => crypto.randomBytes(bytes).toString('hex');

// --- scrypt password hashing ---
function hashPassword(password) {
  const salt = crypto.randomBytes(16).toString('hex');
  const hash = crypto.scryptSync(password, salt, 64, { N: 16384, r: 8, p: 1 }).toString('hex');
  return { salt, hash };
}
function verifyPassword(password, salt, expectedHash) {
  const hash = crypto.scryptSync(password, salt, 64, { N: 16384, r: 8, p: 1 });
  const expected = Buffer.from(expectedHash, 'hex');
  return hash.length === expected.length && crypto.timingSafeEqual(hash, expected);
}

// --- AES-256-GCM for secrets at rest (SNMP communities) ---
function encrypt(plain, secretHex) {
  const key = crypto.createHash('sha256').update(secretHex).digest();
  const iv = crypto.randomBytes(12);
  const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
  const enc = Buffer.concat([cipher.update(String(plain), 'utf8'), cipher.final()]);
  return Buffer.concat([iv, cipher.getAuthTag(), enc]).toString('base64');
}
function decrypt(b64, secretHex) {
  const buf = Buffer.from(b64, 'base64');
  const key = crypto.createHash('sha256').update(secretHex).digest();
  const decipher = crypto.createDecipheriv('aes-256-gcm', key, buf.subarray(0, 12));
  decipher.setAuthTag(buf.subarray(12, 28));
  return Buffer.concat([decipher.update(buf.subarray(28)), decipher.final()]).toString('utf8');
}

// --- token-bucket rate limiter (in-memory) ---
class RateLimiter {
  constructor({ perMinute, burst }) {
    this.rate = perMinute / 60000; // tokens per ms
    this.burst = burst || perMinute;
    this.buckets = new Map();
    // periodic cleanup so idle keys don't leak
    this.cleaner = setInterval(() => {
      const cutoff = now() - 10 * 60 * 1000;
      for (const [k, b] of this.buckets) if (b.ts < cutoff) this.buckets.delete(k);
    }, 5 * 60 * 1000);
    this.cleaner.unref();
  }
  allow(key, cost = 1) {
    const t = now();
    let b = this.buckets.get(key);
    if (!b) { b = { tokens: this.burst, ts: t }; this.buckets.set(key, b); }
    b.tokens = Math.min(this.burst, b.tokens + (t - b.ts) * this.rate);
    b.ts = t;
    if (b.tokens < cost) return false;
    b.tokens -= cost;
    return true;
  }
}

// --- SSE hub for live streams (org-scoped) ---
class SseHub {
  constructor() { this.clients = new Set(); }
  handler(req, res, orgId = DEFAULT_ORG_ID) {
    res.writeHead(200, {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      Connection: 'keep-alive',
      'X-Accel-Buffering': 'no',
    });
    res.write(':ok\n\n');
    const client = { res, orgId };
    this.clients.add(client);
    const ping = setInterval(() => { try { res.write(':ping\n\n'); } catch { /* closed */ } }, 25000);
    req.on('close', () => { clearInterval(ping); this.clients.delete(client); });
  }
  // Only clients belonging to `orgId` receive the message (tenant isolation).
  broadcast(type, data, orgId = DEFAULT_ORG_ID) {
    if (!this.clients.size) return;
    const payload = `event: ${type}\ndata: ${JSON.stringify(data)}\n\n`;
    for (const c of this.clients) {
      if (c.orgId !== orgId) continue;
      try { c.res.write(payload); } catch { this.clients.delete(c); }
    }
  }
}

// --- validation helpers ---
const isStr = (v, max = 500) => typeof v === 'string' && v.length > 0 && v.length <= max;
const optStr = (v, max = 500) => v === undefined || v === null || (typeof v === 'string' && v.length <= max);
const clampInt = (v, min, max, def) => {
  const n = parseInt(v, 10);
  if (!Number.isFinite(n)) return def;
  return Math.min(max, Math.max(min, n));
};
const isEmail = (v) => typeof v === 'string' && /^[^\s@]{1,64}@[^\s@]{1,255}\.[^\s@]{2,}$/.test(v);

function httpError(res, status, message) { res.status(status).json({ error: message }); }

/**
 * HTML-escape for the server-rendered public pages (status page, vendor grid,
 * mails). It lives HERE rather than as a local helper in each of them because
 * the local copies are exactly what broke: pulling the status page out of
 * routes/public.js took `esc` with it, and the vendor grid — which used it too
 * and has no harness — started answering 500 in production. A shared primitive
 * cannot be moved out from under its second caller.
 */
function escapeHtml(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&#39;');
}

/**
 * Primary keys for the two tables an outsider can name: users and organizations.
 *
 * UUIDv4, generated by us rather than by the database. The id is needed BEFORE
 * the row is written — it goes into the membership and the four org settings in
 * the same transaction — so "mint the id, then insert it" is what the call sites
 * want anyway, and it is why these two columns carry no server-side DEFAULT.
 *
 * The column is `UUID`, and the value is a string everywhere in JS: it survives a
 * JSON round trip untouched and reads the same in a log line as in `psql`.
 */
const newId = () => crypto.randomUUID();

/**
 * The default organization, as a FIXED uuid rather than a random one.
 *
 * Single-tenant installs (the whole community edition) and a dozen platform code
 * paths mean "the org" — that used to be the literal `1`, which is exactly the
 * kind of magic number a uuid migration turns into a bug. Naming it keeps those
 * paths honest, keeps the migration deterministic (the old org 1 always lands
 * here, on every install, so a support question can be answered), and keeps the
 * value recognisable in a database dump.
 *
 * Version nibble 4 and variant nibble 8 so it is a well-formed v4 uuid and not a
 * value that only looks like one.
 */
const DEFAULT_ORG_ID = '00000000-0000-4000-8000-000000000001';

/**
 * Shape check for an id arriving from a request.
 *
 * Not a security boundary — every id is still checked against a membership or an
 * `org_id =` in the query. It exists so a malformed value is rejected AS
 * malformed: with integer keys, `parseInt('abc')` produced NaN and NaN quietly
 * meant "no override", which is the kind of guard that reads as working. A uuid
 * is a string, so the equivalent mistake would have been passing 'abc' straight
 * into SQL and getting an empty result set that looks like an empty account.
 */
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const isId = (v) => typeof v === 'string' && UUID_RE.test(v);
const isOrgId = isId;

/* ── UTC day buckets, without asking the database what a day is ──────────────
 *
 * The three analytics charts used `strftime('%Y-%m-%d', ts / 1000, 'unixepoch')`.
 * SQLite renders that in UTC; PostgreSQL has no strftime at all, and its
 * replacement `to_timestamp()` renders in the SESSION TimeZone — so a literal
 * translation shifts every bucket by the server's offset. The charts still look
 * plausible afterwards, which is the whole problem: nothing is empty, nothing
 * errors, the numbers are just attributed to the wrong day.
 *
 * So the database no longer has an opinion. A UTC day IS `ts - ts % 86400000`
 * on an epoch-millisecond column: integer arithmetic, identical on both engines,
 * with no timezone concept anywhere near it. Deliberately not `ts / 86400000`
 * with a CAST — `CAST(float AS INTEGER)` ROUNDS in Postgres and TRUNCATES in
 * SQLite, so a cast would move rows across the midnight boundary on one engine
 * only, which is exactly the class of bug this replaces.
 *
 * The label is formatted here, where 'YYYY-MM-DD' means one thing.
 */
const DAY_MS = 86400000;
/** SQL for the UTC-day bucket of an epoch-millisecond column. */
const utcDaySql = (col) => `${col} - ${col} % ${DAY_MS}`;
/** The bucket value that SQL returns, as the 'YYYY-MM-DD' the API promises. */
const utcDayLabel = (ms) => new Date(Number(ms)).toISOString().slice(0, 10);


/**
 * The canonical form of an HTTP check target — `null` if it cannot be one.
 *
 * A person types `link11.com`, which is a perfectly good thing to monitor and
 * not a URL. Something has to add the scheme, and for a long time TWO things
 * did it differently: the in-process probe prepended `https://`, and the Sensor
 * Agent called `fetch(target)` straight, where undici answers
 *
 *     TypeError: Failed to parse URL from link11.com
 *
 * So the same check passed from Nuremberg and failed from N. Virginia and Los
 * Angeles, with an error message about OUR parser printed where the customer
 * reads "is my site up?". Two implementations of one rule, and the one that
 * drifted was the one running on the customer-facing fleet.
 *
 * The fix is not to copy the line into the agent — it is that the target is
 * canonical BEFORE it is stored, so no runner has an opinion. Both writers go
 * through here and migration 038 backfills; a deployed agent is therefore fixed
 * by the migration alone, without waiting for it to self-update.
 *
 * Only the scheme is added. `new URL` is a validator here, not a formatter:
 * returning `u.href` would rewrite `https://link11.com` to
 * `https://link11.com/` and quietly edit what the customer typed.
 */
function httpTarget(raw) {
  const s = String(raw == null ? '' : raw).trim();
  if (!s) return null;
  const withScheme = /^https?:\/\//i.test(s) ? s : `https://${s}`;
  // `new URL` is the whole validator, and that is deliberate rather than thin.
  // A guard on `u.hostname` was written here first and MEASURED to be dead:
  // for a special scheme the WHATWG parser rejects an empty host outright, so
  // `https://`, `https:///`, `https://:8080` and `https://#x` all throw. The
  // mutation that removed it left all 173 checks green, which is what a
  // redundant line looks like — and a line kept "for safety" with a comment
  // asserting a runtime difference nobody has seen is worse than no line.
  try { new URL(withScheme); } catch { return null; }
  return withScheme;
}

module.exports = {
  now, sha256, randHex, hashPassword, verifyPassword, encrypt, decrypt,
  RateLimiter, SseHub, isStr, optStr, clampInt, isEmail, httpError, escapeHtml,
  newId, DEFAULT_ORG_ID, isId, isOrgId,
  DAY_MS, utcDaySql, utcDayLabel, httpTarget,
};
