'use strict';
/* Translates `src/schema.sql` (SQLite) into PostgreSQL DDL.
 *
 * This is not the migration. It exists so that the ~700 prepared statements in
 * `server/src` can be PREPAREd against a real Postgres — which is the highest-
 * leverage test in docs/POSTGRES-MIGRATION-PLAN.md, because most of those
 * statements have no functional test coverage at all and a prepare-only sweep
 * covers 100% of them for parse errors and type-inference failures.
 *
 * It is a translator, not a hand-maintained file, for the same reason the
 * classifier preview executes the real function: a second copy of the schema
 * would drift, and the copy that drifts is the one the sweep is run against.
 *
 * The type rules come from the plan's §2 and are the interesting part:
 *
 *   INTEGER  → bigint          Every id is fine as int8, and epoch-MILLISECOND
 *                              columns MUST NOT be int4: Postgres int4 overflows
 *                              on 1970-01-25 in milliseconds, so a literal
 *                              INTEGER→integer translation corrupts every
 *                              timestamp on the first insert. bigint everywhere
 *                              is simpler than auditing 91 columns.
 *   …PRIMARY KEY AUTOINCREMENT → bigint GENERATED BY DEFAULT AS IDENTITY.
 *                              "BY DEFAULT" rather than "ALWAYS" on purpose: the
 *                              copier supplies explicit ids, and ALWAYS refuses
 *                              them without OVERRIDING SYSTEM VALUE.
 *   TEXT     → text            Including the JSON-in-TEXT columns: jsonb would
 *                              auto-parse on read and break all 16 JSON.parse
 *                              sites (plan §2, declared non-goal).
 *   REAL     → double precision  NOT `real`. Postgres real is 4-byte, SQLite
 *                              REAL is 8 — a literal translation loses precision
 *                              on latency_ms silently.
 *   BLOB     → bytea
 *   uuid columns → uuid        users.id, organizations.id and the 56 columns
 *                              referencing them. Detected by the DEFAULT holding
 *                              DEFAULT_ORG_ID, or by REFERENCES onto a uuid key.
 *
 * WITHOUT ROWID is dropped (no equivalent; the plan's Phase 8 handles the
 * clustering question). `AUTOINCREMENT`, `COLLATE NOCASE` and SQLite pragmas go
 * with it.
 */
const fs = require('fs');
const path = require('path');

const SCHEMA = path.join(__dirname, '..', 'src', 'schema.sql');

// ── split into statements, keeping comments out of the way ──────────────────
function statements(sql) {
  const out = [];
  let cur = '';
  for (const line of sql.split('\n')) {
    // strip trailing line comments but keep them off the parser's plate
    const noComment = line.replace(/--.*$/, '');
    cur += noComment + '\n';
    if (noComment.trim().endsWith(';')) { out.push(cur.trim()); cur = ''; }
  }
  if (cur.trim()) out.push(cur.trim());
  return out.filter(Boolean);
}

// Tables whose primary key is a TEXT uuid, discovered from the file rather than
// hard-coded: `id TEXT PRIMARY KEY` on a table the app mints ids for.
function uuidTables(stmts) {
  const set = new Set();
  for (const st of stmts) {
    const m = /^CREATE TABLE(?: IF NOT EXISTS)?\s+([A-Za-z0-9_]+)/i.exec(st);
    if (!m) continue;
    if (/\bid\s+TEXT\s+PRIMARY KEY/i.test(st)) set.add(m[1]);
  }
  return set;
}

function translateTable(st, uuids) {
  const name = /^CREATE TABLE(?: IF NOT EXISTS)?\s+([A-Za-z0-9_]+)/i.exec(st)[1];
  let body = st.slice(st.indexOf('(') + 1, st.lastIndexOf(')'));

  const cols = [];
  let depth = 0, cur = '';
  for (const ch of body) {
    if (ch === '(') depth++;
    if (ch === ')') depth--;
    if (ch === ',' && depth === 0) { cols.push(cur); cur = ''; continue; }
    cur += ch;
  }
  if (cur.trim()) cols.push(cur);

  const out = cols.map((raw) => {
    let c = raw.trim();
    if (!c) return null;
    // table-level constraints pass through
    if (/^(PRIMARY KEY|UNIQUE|CHECK|FOREIGN KEY)\b/i.test(c)) return c;

    const colName = /^([A-Za-z0-9_]+)/.exec(c)[1];

    // identity columns
    if (/INTEGER\s+PRIMARY KEY\s+AUTOINCREMENT/i.test(c)) {
      return c.replace(/INTEGER\s+PRIMARY KEY\s+AUTOINCREMENT/i,
        'bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY');
    }
    if (/INTEGER\s+PRIMARY KEY\b/i.test(c)) {
      return c.replace(/INTEGER\s+PRIMARY KEY/i, 'bigint PRIMARY KEY');
    }

    // uuid columns: the table's own TEXT primary key, or a reference to one
    const refs = /REFERENCES\s+([A-Za-z0-9_]+)/i.exec(c);
    const isUuid = (/^\s*id\s+TEXT\s+PRIMARY KEY/i.test(c) && uuids.has(name))
      || (refs && uuids.has(refs[1]) && /\bTEXT\b/i.test(c));
    if (isUuid) c = c.replace(/\bTEXT\b/i, 'uuid');

    return c
      .replace(/\bINTEGER\b/gi, 'bigint')
      .replace(/\bREAL\b/gi, 'double precision')
      .replace(/\bBLOB\b/gi, 'bytea')
      .replace(/\bCOLLATE\s+NOCASE\b/gi, '')
      .replace(/\bAUTOINCREMENT\b/gi, '');
  }).filter(Boolean);

  return `CREATE TABLE ${name} (\n  ${out.join(',\n  ')}\n);`;
}

function translate(sql) {
  const stmts = statements(sql);
  const uuids = uuidTables(stmts);
  const out = [];
  for (const st of stmts) {
    if (/^CREATE TABLE/i.test(st)) {
      // WITHOUT ROWID needs no stripping: translateTable slices to the LAST
      // ')', which is the table's own closing paren either way.
      out.push(translateTable(st, uuids));
    } else if (/^CREATE\s+(UNIQUE\s+)?INDEX/i.test(st)) {
      // `DESC` and partial `WHERE` are the same in both; only IF NOT EXISTS moves
      out.push(st.replace(/\bIF NOT EXISTS\b/i, 'IF NOT EXISTS'));
    } else if (/^(PRAGMA|BEGIN|COMMIT)/i.test(st)) {
      continue;
    } else {
      out.push(st);
    }
  }
  return out.join('\n\n') + '\n';
}

if (require.main === module) {
  process.stdout.write(translate(fs.readFileSync(SCHEMA, 'utf8')));
}
module.exports = { translate };
